### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by MicrocontrollersDev** [karmette/FabricMods#1]
1. Borderless Mining (Windowed fullscreen) - https://www.curseforge.com/minecraft/mc-mods/borderless-mining

2. Krypton (Not 100% sure what this does but some optimizations regarding network stacking. I bet it's more useful server-sided but so is overworld 2 and that's included so) - https://www.curseforge.com/minecraft/mc-mods/krypton/

3. Mobs Main Menu (While not a 1.8 thing, it was very popular in 1.7 and before as it was in bspkrscore) - https://www.curseforge.com/minecraft/mc-mods/mobs-main-menu

4. Starlight (Alternative to Phosphor. It's better than phosphor performance wise, but it's not 100% vanilla and is very experimental) - https://github.com/Spottedleaf/Starlight/releases

5. Custom Crosshair Mod (I don't think I need to explain this lol) - https://www.curseforge.com/minecraft/mc-mods/custom-crosshair-mod/files/3054818

6. Blur (Inventory blur) - https://www.curseforge.com/minecraft/mc-mods/blur-fabric/files

Others (bc too lazy to go find all links and give description):
Smooth Scrolling Everywhere
NumericPing
PerspectiveModRedux
Controlling
AuthMe

**Comment by karmette** [comment]
Didnt add starlight and Krypton but
Borderless Mining and Perspective mod redux were already in there

ok I added the rest :D

**Comment by MicrocontrollersDev** [comment]
> Borderless Mining and Perspective mod redux were already in there

forgive me for i am blind lol
